backend:
  name: git-gateway
  branch: main
media_folder: "src/upload"
public_folder: "/upload"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Zdjęcie", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "string", default: "post" }
      - { label: "Body", name: "body", widget: "markdown" }
